#! /bin/sh

if test -z "${REAL_OPT_DIR}"; then
# next line to be replaced according to OPTWARE_TARGET
REAL_OPT_DIR=/usr/local/AppCentral/optware/opt
fi

case "$1" in
    start)
        echo "Starting Optware."
    ;;
    reconfig)
        echo "Reconfig Optware."
	true
    ;;
    stop)
        echo "Shutting down Optware."
	true
    ;;
    *)
        echo "Usage: $0 {start|stop|reconfig}"
        exit 1
esac

exit 0
